# Generated by Django 3.2.9 on 2021-11-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0, null=True)),
                ('laptop_store_url', models.TextField(null=True)),
                ('laptop_fee_url', models.TextField(null=True)),
                ('laptop_img', models.TextField(null=True)),
                ('cpu_name', models.CharField(max_length=45, null=True)),
                ('cpu_level', models.IntegerField(default=1)),
                ('weight', models.FloatField(null=True)),
                ('ram', models.IntegerField(default=0, null=True)),
                ('battery', models.FloatField(null=True)),
                ('display', models.FloatField(null=True)),
                ('storage_space', models.IntegerField(null=True)),
                ('os_type', models.CharField(default='W', max_length=1)),
                ('touch', models.CharField(default='N', max_length=1)),
                ('first_price', models.FloatField(null=True)),
                ('sales_price', models.FloatField(null=True)),
                ('pd_charge', models.CharField(default='N', max_length=1)),
                ('review', models.IntegerField(null=True)),
                ('final_price', models.FloatField(null=True)),
                ('card_discount', models.CharField(default=0, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_contents', models.CharField(max_length=45, null=True)),
                ('question_describe', models.CharField(max_length=45, null=True)),
                ('question_img', models.TextField(null=True)),
                ('question_type', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Y', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_contents', models.CharField(max_length=45, null=True)),
                ('choice_weight', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='Y', max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
    ]
