# Generated by Django 3.2.9 on 2021-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='laptop_url',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_fee_url',
            field=models.TextField(max_length=45, null=True),
        ),
    ]
