# Generated by Django 3.2.9 on 2021-12-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211209_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop_fee_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_store_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
