# Generated by Django 3.2.9 on 2021-11-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_choice_choice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
    ]
