# Generated by Django 3.2.9 on 2021-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_question_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop_fee_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_store_url',
            field=models.TextField(null=True),
        ),
    ]
