# Generated by Django 3.2.9 on 2021-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211111_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='os_type',
            field=models.CharField(default='N', max_length=45),
        ),
    ]
