# Generated by Django 3.2.9 on 2021-11-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_laptop_os_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='price',
            new_name='first_price',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='sale_price',
            new_name='sales_price',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='charge',
        ),
        migrations.AddField(
            model_name='laptop',
            name='pd_charge',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='card_discount',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os_type',
            field=models.CharField(default='W', max_length=45),
        ),
    ]
