# Generated by Django 3.2.9 on 2021-11-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211111_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='battery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os_type',
            field=models.CharField(default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_space',
            field=models.IntegerField(null=True),
        ),
    ]
