# Generated by Django 3.2.9 on 2021-11-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211111_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='status',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='battery',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='card_discount',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(default='Y', max_length=1, null=True),
        ),
    ]
